--liquibase formatted sql

--changeset Giang:2


INSERT INTO role VALUES (1,'ROLE_ADMIN'),(2,'ROLE_USER');

INSERT INTO seat_type VALUES (1,'Classic'),(2,'VIP');

INSERT INTO user VALUES
(1,NULL,NULL,NULL,NULL,NULL,'Jack',NULL,NULL,'Daniel','${ADMIN_PASSWORD}',NULL,NULL,NULL,NULL,NULL,'${ADMIN_USERNAME}'),
(2,NULL,NULL,NULL,NULL,NULL,'Tullamore',NULL,NULL,'Dev','${USER1_PASSWORD}',NULL,NULL,NULL,NULL,NULL,'${USER1_USERNAME}'),
(3,NULL,NULL,NULL,NULL,NULL,'Jager',NULL,NULL,'Meister','${USER2_PASSWORD}',NULL,NULL,NULL,NULL,NULL,'${USER2_USERNAME}');

INSERT INTO user_roles VALUES (1,1),(2,2),(3,2);